[build-system]
requires = ["setuptools>=64", "setuptools_scm[toml]>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "fmri-codecs"
dynamic = ["version"]
description = "fMRI compression codecs"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "datasets",
    "einops",
    "ipython",
    "jupyter",
    "matplotlib",
    "neuromaps",
    "nibabel",
    "numpy",
    "omegaconf",
    "pre-commit",
    "pycortex>=1.2.11",
    "pytest",
    "scikit-learn",
    "scipy",
    "tabulate",
    "torch",
    "yaspy",
    "zstd",
]

[tool.uv.sources]
yaspy = { git = "https://github.com/childmindresearch/yaspy.git" }

[tool.setuptools_scm]
version_file = "src/fmri_codecs/_version.py"

[tool.ruff]
line-length = 100

[tool.ruff.lint]
ignore = ["F722"]
