import numpy as np


class Codec:
    """Base interface for fmri codecs."""

    def encode(self, x: np.ndarray) -> bytes: ...

    def decode(self, buf: bytes) -> np.ndarray: ...

    def fit(self, X: list[np.ndarray]) -> "Codec": ...

    def hparams(self) -> dict[str, int | float | str]: ...

    def __str__(self) -> str: ...

    def __repr__(self) -> str: ...
